# Generated by Django 3.1.6 on 2021-03-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('unique_id', models.CharField(max_length=200)),
                ('zip_code_prefix', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code_prefix', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
