# Generated by Django 3.1.6 on 2021-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
