# Generated by Django 3.1.6 on 2021-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0003_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.CharField(max_length=50)),
                ('payment_sequential', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_installments', models.IntegerField()),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
