# Generated by Django 3.1.6 on 2021-03-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0004_orderpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_uuid', models.CharField(max_length=50)),
                ('order_uuid', models.CharField(max_length=50)),
                ('review_score', models.IntegerField()),
                ('review_comment_title', models.TextField()),
                ('review_comment_message', models.TextField()),
                ('review_creation_date', models.DateTimeField()),
                ('review_answer_timestamp', models.DateTimeField()),
            ],
        ),
    ]
