# Generated by Django 3.1.6 on 2021-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
