# Generated by Django 3.1.6 on 2021-03-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0010_auto_20210305_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
