# Generated by Django 3.1.6 on 2021-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0011_auto_20210305_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
