# Generated by Django 3.1.6 on 2021-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0014_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNameTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_name_english', models.CharField(max_length=200)),
            ],
        ),
    ]
