# Generated by Django 3.1.6 on 2021-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0015_categorynametranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_uuid', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
