# Generated by Django 3.1.6 on 2021-03-22 14:33

from django.db import migrations


class Migration(migrations.Migration):
    # necessary becasue concurrent migration application
    # cannot happen inside a transaction.
    atomic = False

    dependencies = [
        ('mercado_brasileiro', '0016_selleruser'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX CONCURRENTLY "order_items_on_seller_uuid" '
            'ON "mercado_brasileiro_orderitem" ("seller_uuid");',
        ),
    ]
