# Generated by Django 3.1.6 on 2021-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0017_index_order_items_by_seller_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_uuid', models.CharField(max_length=50)),
                ('product_uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('owned', models.BooleanField()),
                ('available', models.BooleanField()),
                ('wholesale_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
