# Generated by Django 3.1.6 on 2021-04-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0018_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_unique_id', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
