# Generated by Django 3.1.6 on 2021-04-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0019_customeruser'),
    ]

    operations = [
        migrations.RunSQL(
        """
        CREATE OR REPLACE VIEW merchant_ranking AS
            SELECT mbs.id AS seller_id,
              COUNT(mbor.review_score) AS review_count,
              AVG(mbor.review_score) AS mean_score
            FROM mercado_brasileiro_orderreview mbor
            INNER JOIN mercado_brasileiro_order mbo
              ON mbor.order_uuid = mbo.order_uuid
            INNER JOIN mercado_brasileiro_orderitem mboi
              ON mboi.order_uuid = mbo.order_uuid
            INNER JOIN mercado_brasileiro_seller mbs
              ON mbs.seller_uuid = mboi.seller_uuid
            GROUP BY mbs.id;
        """
        ),
    ]
