# Generated by Django 3.1.6 on 2021-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0020_add_ranking_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('mean_score', models.FloatField()),
            ],
            options={
                'db_table': 'merchant_ranking',
                'managed': False,
            },
        ),
    ]
