# Generated by Django 3.1.6 on 2021-04-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0021_merchantranking'),
    ]

    operations = [
        migrations.RunSQL(
        """
        CREATE OR REPLACE VIEW merchant_rank_percentile AS
            SELECT seller_id,
              review_count,
              mean_score,
              PERCENT_RANK() over (ORDER BY mean_score) AS percentile
            FROM merchant_ranking;
        """
        ),
    ]
