# Generated by Django 3.1.6 on 2021-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0022_create_ranking_percentile_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='inventory_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterModelTable(
            name='merchantranking',
            table='merchant_rank_percentile',
        ),
    ]
