# Generated by Django 3.1.6 on 2021-04-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0024_inventory_value_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW order_predicted_score AS
                SELECT 
                  mboi.*,
                  100 AS predicted_score
                FROM mercado_brasileiro_orderitem mboi
                INNER JOIN mercado_brasileiro_seller mbs
                  ON mbs.seller_uuid = mboi.seller_uuid
                ;
            """
        ),
    ]