# Generated by Django 3.1.6 on 2021-04-04 19:21

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0025_add_order_predicted_score_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPredictedScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.CharField(max_length=50)),
                ('order_item_id', models.IntegerField()),
                ('product_uuid', models.CharField(max_length=50)),
                ('seller_uuid', models.CharField(max_length=50)),
                ('shipping_limit_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('freight_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_score', models.FloatField()),
            ],
            options={
                'db_table': 'order_predicted_score',
                'managed': False,
            },
        ),
    ]