# Generated by Django 3.1.6 on 2021-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_brasileiro', '0025_OrderPredictedSatisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpredictedsatisfaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderpredictedsatisfaction',
            name='carrier_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderpredictedsatisfaction',
            name='delivered_customer_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
